version: '3'

services:
        db:
                image: postgres
                volumes:
                - "ssodbdata:/var/lib/postgresql/data"
                environment:
                - POSTGRES_DB=postgres
                - POSTGRES_USER=postgres
                - POSTGRES_PASSWORD=postgres
        web:
                build: .
                ports:
                        - "8000:8000"
                depends_on:
                        - db
volumes:
        ssodbdata:

